### ISSUE TITLE
tracking: cleanup examples

### ISSUE THREAD

**Issue by kaspar030** [ariel-os/ariel-os#410]
### Description

Initial targeted list of examples in this [pad](https://pad.riot-os.org/aPbbp77KTEKZb--l6GwdUA?both).

For each example,

- [ ] minimize
- [ ] check name
  - [ ] no embassy
  - [ ] no async, is default
  - [ ] "-threading"
- [ ] polish
- [ ] use `ariel_os::reexports` when relevant
- [ ] use the `tcp` and `udp` Cargo features introduced by #525, instead of depending on `embassy-net`
- [ ] Be consistent in the usage of laze modules vs ariel_os features.
- [ ] has entry in `examples/README.md`

Please copy this list into cleanup PRs!

#### Missing examples

- [x] CoAP Minimal server -- static hello world -> coap-server TODO
- [x] CoAP Minimal client -- get pre-configured resource -> coap-client TODO
- [ ] i2c demonstrator
- [ ] spi demonstrator

### Tracking

From [pad](https://pad.riot-os.org/aPbbp77KTEKZb--l6GwdUA?both): 

- [ ] benchmark
- [x] blinky
- [ ] Secure LED blinking over CoAP + OSCORE -> coap-blinky TODO
- [ ] coap-client
- [ ] coap-server
- [x] core-sizes (move to tests/, turn into regression test?) removed by #563
- [x] device-metadata #608 
- [x] gpio #611 
- [x] ~hello-world-async~ -> hello-world (maybe becoming blinky-async?( K: no, why?)) #478
- [x] ~hello-world~ -> hello-world-threading #478 
- [x] http-client #627
- [x] ~embassy-http-server~ -> http-server #570
- [x] log #547 
- [ ] multicore-affinities
- [x] random #562
- [x] storage #676
- [x] ~embassy-net-tcp~ -> tcp-echo #522
- [x] ~embassy~ -> thread-async-interop #505 
- [x] threading #605 
- [x] threading-channel #607
- [x] threading-event #606
- [ ] threading-multicore
- [x] ~embassy-net-udp~ -> udp-echo #521
- [x] usb-keyboard #538
- [x] usb-serial #573

**Comment by elenaf9** [comment]
- Be consistent in the usage of laze modules vs `riot_rs` features.

**Comment by emmanuelsearch** [comment]
Consider adding examples on
- basics: eg timers, sensor abstraction etc. inspired by RIOT-course https://riot-os.github.io/riot-course/slides/03-riot-basics/#11
- security: hash, sign, encrypt etc. inspired by RIOT-course on sec. https://riot-os.github.io/riot-course/slides/06-security-with-riot/#14

**Comment by bergzand** [comment]
sufficiently fixed with #792 merged
