### ISSUE TITLE
tracking: high-level doc brushup

### ISSUE THREAD

**Issue by emmanuelsearch** [ariel-os/ariel-os#589]
### Description

- mdbook
  - [x] intro/manifesto/why-how-what text revamp/consolidation  #683 (@emmanuelsearch / @bergzand)
  - [x] update arch diagram #655  (@emmanuelsearch / @ROMemories )
  - [x] update the support matrix (@ROMemories / @kaspar030) #702 #716 (others may follow)
  - [x] testing documentation (@kaspar030 / @ROMemories) #698

- [x]  initial FAQ (@emmanuelsearch / @bergzand ) #794

- [x] update roadmap: what's done / what's ongoing (@emmanuelsearch / @kaspar030 )
- [x] *homepage* of the [rustdoc docs](https://ariel-os.github.io/ariel-os/dev/docs/api/ariel_os/index.html) (@bergzand / @emmanuelsearch ) #744 

- main readme
  - [x] revamp umbrella text #681 (@emmanuelsearch / @bergzand)
  - [x] brushup the "Quick Start" page (@bergzand / @emmanuelsearch ) #739
  - [x] Copyright years #681 (@emmanuelsearch / @bergzand)
  - [x] Reconsider the "Supported hardware" section, point to the [support matrix](https://ariel-os.github.io/ariel-os/dev/docs/book/hardware_functionality_support.html) instead? #681 (@bergzand / @emmanuelsearch )
  - [x] Replacing the "Coding Conventions" section with a "Contributing" section, pointing to `CONTRIBUTING.md`, which itself already refers to the Coding Conventions #736
  - [x] #730
  - [x] Title case consistency (@emmanuelsearch / @bergzand)
- [x] `doc` root directory (@ROMemories  / @kaspar030) #671 #672
- [x] [`ariel-os-threads/README.md`](https://github.com/ariel-os/ariel-os/blob/main/src/ariel-os-threads/README.md) needs an update/to be removed (@kaspar030 /@romemories) #680

### Motivation

Current state of these docs is outdated and has redundancies.

### Current Implementation

See current state of these documents.

### Are you planning to do it yourself in a pull request?

Yes

**Comment by emmanuelsearch** [comment]
We're done with this at this stage.
